server:
  port: 8002

mybatis:   # mybatis配置
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: club.huangliang.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml


spring:
  application:
    name: ssg-springcloud-dept
  datasource:    #数据源采用阿里巴巴的数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudbasedb1
    username: root
    password: 178290
    dbcp2:
      min-idle: 5          # 数据库链接池的最小维持链接数
      initial-size: 5      # 初始化链接数
      max-total: 5         #最大链接数
      max-wait-millis: 200    #等待链接获取的最大超时时间
  #将服务注册到eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

  instance:
    instance-id: ssg_springcloud-dept8002  #为注册进eureka服务器的服务取别名（实例名）
    prefer-ip-address: true  #访问路径可以显示ip地址
info:
  app.name: ssg_springcloud-provider-dept-8002
  company.name: www.huangliang.club
  build.artifactId: "@project.artifactId@"   #1.5.9应该可以使用$$,而2.0.x应该是@…@
  build.version: "@project.version@"